services:
    buildbox:
        build:
            context: .
            target: dev
        volumes:
            - .:/app
            - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
        environment:
            - COMPOSER_AUTH
            - SSH_AUTH_SOCK=/ssh-agent
            - TIMEZONE=${TIMEZONE:-}
            - MAX_DATE_DRIFT=${MAX_DATE_DRIFT:-}

    builder:
        build:
            context: .
            target: builder
            args:
                USERID: ${USERID}
                GROUPID: ${GROUPID}
        volumes:
            - ./:/renamer
        working_dir: /renamer
        user: "renamer"
