services:
    buildbox:
        build:
            context: .
            target: dev
        volumes:
            - .:/app
            - ~/.ssh:/root/.ssh:ro
        environment:
            - COMPOSER_AUTH

    builder:
        build:
            context: .
            target: builder
            args:
                USERID: ${USERID}
                GROUPID: ${GROUPID}
        volumes:
            - ./:/renamer
        working_dir: /renamer
        user: "renamer"
