#!/usr/bin/env bash

set -e # Instructs a shell to exit if a command fails, i.e., if it outputs a non-zero exit status.

PHP_EXTENSIONS="curl,dom,exif,fileinfo,filter,intl,mbstring,opcache,openssl,pcntl,phar,posix,readline,session,tokenizer,yaml,zip,zlib"

cd $(dirname "${BASH_SOURCE[0]}")

cd ..

if [ -f 'spc/buildroot/bin/micro.sfx' ]; then
    echo "Found micro.sfx we consider SPC already built"
    exit 0
fi

if [ ! -d "spc" ]; then
    mkdir spc
fi

if [ ! -f "bin/spc" ]; then
    echo "Download SPC binary command"
    curl -fsSL -o bin/spc https://dl.static-php.dev/static-php-cli/spc-bin/nightly/spc-linux-x86_64
    # Add execute perm (Linux and macOS only)
    chmod +x bin/spc
fi

cd spc

echo "Check system tool dependencies, auto-fix them if possible"
../bin/spc doctor --auto-fix

echo "Download UPX command"
../bin/spc install-pkg upx

echo "Download SPC extensions"
../bin/spc download --with-php=8.3 --for-extensions "${PHP_EXTENSIONS}" --prefer-pre-built

echo "Compile SPC"
../bin/spc build --build-cli --build-micro --with-micro-fake-cli --with-upx-pack "${PHP_EXTENSIONS}" -I "phar.readonly=Off" -I "memory_limit=4G"

ln -sf ../spc/buildroot/bin/php ../bin/php

echo "Install Composer"
curl -fsSL -o composer-setup.php https://getcomposer.org/installer

if [ ! -f "composer-setup.php" ]; then
    echo "Composer download failed"
    exit 1
fi

../bin/php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
../bin/php composer-setup.php && \
../bin/php -r "unlink('composer-setup.php');"

if [ -f "composer.phar" ]; then
    ../bin/spc micro:combine composer.phar --output=composer
    rm composer.phar
    mv composer ../bin/composer
else
    echo "Composer download failed"
    exit 1
fi
