#!/usr/bin/env bash

set -e # Instructs a shell to exit if a command fails, i.e., if it outputs a non-zero exit status.

# Add only the PHP extensions that are really required to reduce the size of the final binary file
PHP_EXTENSIONS="curl,dom,exif,filter,mbstring,openssl,pcntl,phar,posix,tokenizer,yaml,zlib"
#PHP_EXTENSIONS="curl,dom,exif,fileinfo,filter,intl,mbstring,opcache,openssl,pcntl,phar,posix,readline,session,tokenizer,yaml,zip,zlib"

cd $(dirname "${BASH_SOURCE[0]}")

cd ..

if [ -f 'spc/buildroot/bin/micro.sfx' ]; then
    echo "Delete existing buildroot/ and source/ directories to start a new build from scratch"
    rm -rf spc/buildroot spc/source
fi

if [ ! -d "spc" ]; then
    mkdir spc
fi

if [ ! -f "bin/spc" ]; then
    echo "Download SPC binary command"
    curl -fsSL -o bin/spc https://dl.static-php.dev/static-php-cli/spc-bin/nightly/spc-linux-x86_64
    # Add execute permission (Linux and macOS only)
    chmod +x bin/spc
fi

cd spc

echo "Check system tool dependencies, auto-fix them if possible"
../bin/spc doctor --auto-fix

if [ ! -f "spc/pkgroot/bin/upx" ]; then
    echo "Download UPX command"
    ../bin/spc install-pkg upx
fi

echo "Download SPC extensions"
../bin/spc download --with-php=8.3 --for-extensions "${PHP_EXTENSIONS}" --prefer-pre-built --without-suggestions

echo "Compile SPC"
../bin/spc build --build-cli --build-micro --with-micro-fake-cli --with-upx-pack "${PHP_EXTENSIONS}" -I "phar.readonly=Off" -I "memory_limit=4G"

ln -sf ../spc/buildroot/bin/php ../bin/php

echo "Install Composer"
curl -fsSL -o composer-setup.php https://getcomposer.org/installer

if [ ! -f "composer-setup.php" ]; then
    echo "Composer download failed"
    exit 1
fi

EXPECTED_CHECKSUM="$(../bin/php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
ACTUAL_CHECKSUM="$(../bin/php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid Composer installer checksum'
    rm composer-setup.php
    exit 1
fi

../bin/php composer-setup.php && \
../bin/php -r "unlink('composer-setup.php');"

if [ -f "composer.phar" ]; then
    ../bin/spc micro:combine composer.phar --output=composer
    rm composer.phar
    mv composer ../bin/composer
else
    echo "Composer download failed"
    exit 1
fi
