<?php

namespace MagicSunday\Renamer;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\LogicException;
use Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Component\DependencyInjection\ParameterBag\FrozenParameterBag;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class DependencyContainer extends Container
{
    protected $parameters = [];

    public function __construct()
    {
        $this->services = $this->privates = [];
        $this->syntheticIds = [
            'Symfony\\Component\\Console\\Style\\SymfonyStyle' => true,
        ];
        $this->methodMap = [
            'MagicSunday\\Renamer\\Application' => 'getApplicationService',
        ];

        $this->aliases = [];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return [
            'MagicSunday\\ImageMeta\\MetadataReader' => true,
            'MagicSunday\\Renamer\\Command\\FilterIterator\\RecursiveRegexFileFilterIterator' => true,
            'MagicSunday\\Renamer\\Command\\FilterIterator\\RecursiveUppercaseFilenameFilterIterator' => true,
            'MagicSunday\\Renamer\\Command\\RenameByDatePatternCommand' => true,
            'MagicSunday\\Renamer\\Command\\RenameByExifDateCommand' => true,
            'MagicSunday\\Renamer\\Command\\RenameByHashCommand' => true,
            'MagicSunday\\Renamer\\Command\\RenameByPatternCommand' => true,
            'MagicSunday\\Renamer\\Command\\RenameLowerCaseCommand' => true,
            'MagicSunday\\Renamer\\Dependencies' => true,
            'MagicSunday\\Renamer\\Exception\\ExifMetadataReadException' => true,
            'MagicSunday\\Renamer\\Exception\\FileReadException' => true,
            'MagicSunday\\Renamer\\Exception\\HashComputationException' => true,
            'MagicSunday\\Renamer\\Exception\\RegexExecutionException' => true,
            'MagicSunday\\Renamer\\Exception\\TargetFilenameException' => true,
            'MagicSunday\\Renamer\\Model' => true,
            'MagicSunday\\Renamer\\Renamer' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\LivePhotoBasenameTargetMap' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\LivePhotoContentIdentifierTarget' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\LivePhotoContentIdentifierTargetMap' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\LivePhotoExistingFilePathnameIndex' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\LivePhotoPairing' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\LivePhotoPairingCollection' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\RegexMatchAllResult' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\RegexMatchResult' => true,
            'MagicSunday\\Renamer\\Service\\Dto\\TemporalMetadata' => true,
            'MagicSunday\\Renamer\\Service\\DuplicateDetectionService' => true,
            'MagicSunday\\Renamer\\Service\\DuplicateDetectionServiceInterface' => true,
            'MagicSunday\\Renamer\\Service\\FileSystemService' => true,
            'MagicSunday\\Renamer\\Service\\FileSystemServiceInterface' => true,
            'MagicSunday\\Renamer\\Service\\LivePhotoPairingService' => true,
            'MagicSunday\\Renamer\\Service\\MetadataExtractor' => true,
            'MagicSunday\\Renamer\\Service\\MetadataExtractorInterface' => true,
            'MagicSunday\\Renamer\\Service\\SafeFileReader' => true,
            'MagicSunday\\Renamer\\Service\\SafeHashCalculator' => true,
            'MagicSunday\\Renamer\\Service\\SafeRegex' => true,
            'MagicSunday\\Renamer\\Strategy\\DuplicateIdentifierStrategy\\ContentHashStrategy' => true,
            'MagicSunday\\Renamer\\Strategy\\DuplicateIdentifierStrategy\\LivePhotoContentIdentifierStrategy' => true,
            'MagicSunday\\Renamer\\Strategy\\DuplicateIdentifierStrategy\\TargetFilenameStrategy' => true,
            'MagicSunday\\Renamer\\Strategy\\DuplicateIdentifierStrategy\\TargetPathnameStrategy' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\DatePatternFilenameStrategy' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\Dto\\ContentIdentifier' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\Dto\\ExifData' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\Dto\\RegexMatchCollection' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\Dto\\RegexMatchGroup' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\ExifDateFilenameStrategy' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\ExifMetadataProvider' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\InheritFilenameStrategy' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\LowerCaseFilenameStrategy' => true,
            'MagicSunday\\Renamer\\Strategy\\RenameStrategy\\PatternFilenameStrategy' => true,
        ];
    }

    /**
     * Gets the public 'MagicSunday\Renamer\Application' shared autowired service.
     *
     * @return \MagicSunday\Renamer\Application
     */
    protected static function getApplicationService($container)
    {
        return $container->services['MagicSunday\\Renamer\\Application'] = new \MagicSunday\Renamer\Application(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['MagicSunday\\Renamer\\Command\\RenameByDatePatternCommand'] ?? self::getRenameByDatePatternCommandService($container));
            yield 1 => ($container->privates['MagicSunday\\Renamer\\Command\\RenameByExifDateCommand'] ?? self::getRenameByExifDateCommandService($container));
            yield 2 => ($container->privates['MagicSunday\\Renamer\\Command\\RenameByHashCommand'] ?? self::getRenameByHashCommandService($container));
            yield 3 => ($container->privates['MagicSunday\\Renamer\\Command\\RenameByPatternCommand'] ?? self::getRenameByPatternCommandService($container));
            yield 4 => ($container->privates['MagicSunday\\Renamer\\Command\\RenameLowerCaseCommand'] ?? self::getRenameLowerCaseCommandService($container));
        }, 5));
    }

    /**
     * Gets the private 'MagicSunday\Renamer\Command\RenameByDatePatternCommand' shared autowired service.
     *
     * @return \MagicSunday\Renamer\Command\RenameByDatePatternCommand
     */
    protected static function getRenameByDatePatternCommandService($container)
    {
        return $container->privates['MagicSunday\\Renamer\\Command\\RenameByDatePatternCommand'] = new \MagicSunday\Renamer\Command\RenameByDatePatternCommand(($container->privates['MagicSunday\\Renamer\\Service\\FileSystemServiceInterface'] ??= new \MagicSunday\Renamer\Service\FileSystemService(($container->services['Symfony\\Component\\Console\\Style\\SymfonyStyle'] ?? $container->get('Symfony\\Component\\Console\\Style\\SymfonyStyle', 1)))), ($container->privates['MagicSunday\\Renamer\\Service\\DuplicateDetectionServiceInterface'] ?? self::getDuplicateDetectionServiceInterfaceService($container)), ($container->privates['MagicSunday\\Renamer\\Service\\SafeRegex'] ??= new \MagicSunday\Renamer\Service\SafeRegex()));
    }

    /**
     * Gets the private 'MagicSunday\Renamer\Command\RenameByExifDateCommand' shared autowired service.
     *
     * @return \MagicSunday\Renamer\Command\RenameByExifDateCommand
     */
    protected static function getRenameByExifDateCommandService($container)
    {
        return $container->privates['MagicSunday\\Renamer\\Command\\RenameByExifDateCommand'] = new \MagicSunday\Renamer\Command\RenameByExifDateCommand(($container->privates['MagicSunday\\Renamer\\Service\\FileSystemServiceInterface'] ??= new \MagicSunday\Renamer\Service\FileSystemService(($container->services['Symfony\\Component\\Console\\Style\\SymfonyStyle'] ?? $container->get('Symfony\\Component\\Console\\Style\\SymfonyStyle', 1)))), ($container->privates['MagicSunday\\Renamer\\Service\\DuplicateDetectionServiceInterface'] ?? self::getDuplicateDetectionServiceInterfaceService($container)), new \MagicSunday\Renamer\Strategy\RenameStrategy\ExifMetadataProvider(new \MagicSunday\Renamer\Service\MetadataExtractor(\MagicSunday\ImageMeta\MetadataReader::createDefault())), new \MagicSunday\Renamer\Service\LivePhotoPairingService());
    }

    /**
     * Gets the private 'MagicSunday\Renamer\Command\RenameByHashCommand' shared autowired service.
     *
     * @return \MagicSunday\Renamer\Command\RenameByHashCommand
     */
    protected static function getRenameByHashCommandService($container)
    {
        return $container->privates['MagicSunday\\Renamer\\Command\\RenameByHashCommand'] = new \MagicSunday\Renamer\Command\RenameByHashCommand(($container->privates['MagicSunday\\Renamer\\Service\\FileSystemServiceInterface'] ??= new \MagicSunday\Renamer\Service\FileSystemService(($container->services['Symfony\\Component\\Console\\Style\\SymfonyStyle'] ?? $container->get('Symfony\\Component\\Console\\Style\\SymfonyStyle', 1)))), ($container->privates['MagicSunday\\Renamer\\Service\\DuplicateDetectionServiceInterface'] ?? self::getDuplicateDetectionServiceInterfaceService($container)), new \MagicSunday\Renamer\Service\SafeHashCalculator());
    }

    /**
     * Gets the private 'MagicSunday\Renamer\Command\RenameByPatternCommand' shared autowired service.
     *
     * @return \MagicSunday\Renamer\Command\RenameByPatternCommand
     */
    protected static function getRenameByPatternCommandService($container)
    {
        return $container->privates['MagicSunday\\Renamer\\Command\\RenameByPatternCommand'] = new \MagicSunday\Renamer\Command\RenameByPatternCommand(($container->privates['MagicSunday\\Renamer\\Service\\FileSystemServiceInterface'] ??= new \MagicSunday\Renamer\Service\FileSystemService(($container->services['Symfony\\Component\\Console\\Style\\SymfonyStyle'] ?? $container->get('Symfony\\Component\\Console\\Style\\SymfonyStyle', 1)))), ($container->privates['MagicSunday\\Renamer\\Service\\DuplicateDetectionServiceInterface'] ?? self::getDuplicateDetectionServiceInterfaceService($container)), ($container->privates['MagicSunday\\Renamer\\Service\\SafeRegex'] ??= new \MagicSunday\Renamer\Service\SafeRegex()));
    }

    /**
     * Gets the private 'MagicSunday\Renamer\Command\RenameLowerCaseCommand' shared autowired service.
     *
     * @return \MagicSunday\Renamer\Command\RenameLowerCaseCommand
     */
    protected static function getRenameLowerCaseCommandService($container)
    {
        return $container->privates['MagicSunday\\Renamer\\Command\\RenameLowerCaseCommand'] = new \MagicSunday\Renamer\Command\RenameLowerCaseCommand(($container->privates['MagicSunday\\Renamer\\Service\\FileSystemServiceInterface'] ??= new \MagicSunday\Renamer\Service\FileSystemService(($container->services['Symfony\\Component\\Console\\Style\\SymfonyStyle'] ?? $container->get('Symfony\\Component\\Console\\Style\\SymfonyStyle', 1)))), ($container->privates['MagicSunday\\Renamer\\Service\\DuplicateDetectionServiceInterface'] ?? self::getDuplicateDetectionServiceInterfaceService($container)));
    }

    /**
     * Gets the private 'MagicSunday\Renamer\Service\DuplicateDetectionServiceInterface' shared autowired service.
     *
     * @return \MagicSunday\Renamer\Service\DuplicateDetectionService
     */
    protected static function getDuplicateDetectionServiceInterfaceService($container)
    {
        return $container->privates['MagicSunday\\Renamer\\Service\\DuplicateDetectionServiceInterface'] = new \MagicSunday\Renamer\Service\DuplicateDetectionService(($container->privates['MagicSunday\\Renamer\\Service\\FileSystemServiceInterface'] ??= new \MagicSunday\Renamer\Service\FileSystemService(($container->services['Symfony\\Component\\Console\\Style\\SymfonyStyle'] ?? $container->get('Symfony\\Component\\Console\\Style\\SymfonyStyle', 1)))), ($container->services['Symfony\\Component\\Console\\Style\\SymfonyStyle'] ?? $container->get('Symfony\\Component\\Console\\Style\\SymfonyStyle', 1)));
    }
}
